words:
  - acceelerandos
  - ADDME
  - aleksi
  - alexdumo
  - apikey
  - apos
  - aren
  - asar
  - autoincrement
  - autoplay
  - avenir
  - barline
  - barlines
  - bbox
  - behance
  - Bézier
  - BFSL
  - Bilby
  - blockmap
  - blockqoute
  - bostick
  - BRHS
  - canvas
  - Catmull
  - ccpa
  - Chakravarthi
  - CHANGEME
  - choco
  - Cinnaminson
  - clsx
  - codegen
  - colours
  - Configuración
  - cooldown
  - couldn
  - customizer
  - dbstat
  - DELME
  - Dhruva
  - dorico
  - drumline
  - dukc
  - Dumouchelle
  - Ehhh
  - ehlert
  - endzone
  - endzones
  - esbenp
  - Español
  - evented
  - fielddots
  - fieldots
  - forwardslash
  - frontfield
  - Geral
  - GLHF
  - Hipp
  - idioma
  - Invalidators
  - launchpage
  - lightridge
  - localappdata
  - Macbook's
  - madripoor
  - measurenb
  - mello
  - merch
  - Meuli
  - midset
  - midsets
  - monokai
  - Moulse
  - multiselection
  - musescore
  - musicxml
  - Nativewind
  - notarytool
  - NSIS
  - nums
  - NURBS
  - oklch
  - openmarch
  - openmarchdev
  - overscan
  - pagewidth
  - paperplane
  - partialize
  - pfps
  - Português
  - posthog
  - Pressable
  - PWDEBUG
  - Rcoords
  - rgba
  - ritardandos
  - rootfile
  - saario
  - samuelmeuli
  - Schachner
  - seti
  - shouldn
  - sicommand
  - signtool
  - signup
  - skeuo
  - skiplink
  - skyrim
  - snapcraft
  - sonner
  - spinbutton
  - spms
  - sqljs
  - Sunbright
  - supabase
  - svgs
  - tabler
  - Tamagui
  - Titlebar
  - togglefullscreen
  - toks
  - tolgee
  - Tolgee
  - Topbar
  - trackpad
  - trackpads
  - Tribbiani
  - turborepo
  - umami
  - Uncurried
  - undoable
  - undocs
  - ungroup
  - unistyles
  - unmaximize
  - unpreview
  - uuidv
  - vertaal
  - viewbox
  - viewports
  - vilag
  - vite
  - vitest
  - VMEA
  - vmin
  - Vree
  - WASD
  - wavesurfer
  - winget
  - Woodgrove
  - xlink
  - XMLID
  - yeskunallumami
  - zier
  - Zingali
  - 日本語
ignorePaths:
  - node_modules/**
  - "**/node_modules/**"
  - "**/dist/**"
  - dist/**
  - "**/build/**"
  - "**/src/assets"
  - "**/package.json"
  - "**/.astro/**"
  - "**/.turbo/**"
  - "**/locales/**"
  - locales/**
  - patreonMembers.json
  - "**/mock-databases/**"
  - "**/_journal.json"
  - pnpm-lock.yaml
  - apps/desktop/release/**
  - "**/target/**"
  - patches/canvas.patch
  - apps/desktop/e2e/Dockerfile
  - "**/dist-electron/**"
  - "**/wasm/pkg/**"
  - "*.svg"
  - "*.musicxml"
  - pnpm-workspace.yaml
  - .vscode/extensions.json
ignoreRegExpList:
  - "@[a-z\\-]+"
  - \(#.*\)
  - \u[0-9A-Fa-f]{4}
overrides:
  - filename:
      - "**/i18n/**"
    enabled: false
  - filename:
      - "**/i18n/en.json"
    enabled: true
